### ISSUE TITLE
Explore MongoDB connection and code structure in Synquesticon

### ISSUE THREAD

**Issue by synquesticon** [synopticon/synquesticon#28]
Continue exploration of MongoDB, with focus on:
- How is the DB for the task definitions (editor DB) structured, e.g. if we want to make a single variable for componentVariant of the button component (singleChoice, multipleChoice, selfResetting), how would we do that? If we wanted to add a new component type (e.g. "Video"), how would we do that?
- How is the DB initialized when a fresh installation of Synquesticon is started for the first time?
- How can we set up a separate DB table for the element-level logging (individual button presses, clicks on images, etc.)?
- How do we change the labels in the database (e.g. "participantID")?
- How do we write the logObject to the DB, and what changes are necessary if we want to add/delete/change variables in the log object in the future?
- Look into the data export code, in particular how much custom processing is done during the export (or is it just a matter of serializing the data fields?) How would we change the order of fields in the exported .csv file (since we may want to order the variables in the .csv file from most to least important)?

**Comment by tailyer** [comment]
1. **How is the DB initialized when a fresh installation of Synquesticon is started for the first time?**
A package mongoose will help define and insert Schema for the database.

2. ** a. How is the DB for the task definitions (editor DB) structured, e.g. if we want to make a single variable for componentVariant of the button component (singleChoice, multipleChoice, selfResetting), how would we do that? b. If we wanted to add a new component type (e.g. "Video"), how would we do that?**
a 

- From data_schema.js

Inside data_schema.js, in the SynquestitaskSchema (in accordance to Task definition), there is a childObj array that holds the list of task components. In childObj list, we can add a "componentVariant" field with type String to determine the variant of the button.

- From db_objects.js

Inside a class defining the SynquestitaskChildComponent, add a "componentVariant" variable in the constructor

b. A new type of task component can be added and distinguished with the other types by the field "objType". It is defined as a constant TaskTypes in db_objects.
From Database Object (core/db_objects.js)

3. **How can we set up a separate DB table for the element-level logging (individual button presses, clicks on images, etc.)?**

- Define a new Schema (aka collection) in the data_schema.js. 
- Define a new class in the db_objects.js for this event.
- Generate an api to communicate with the server for this event (for example /api/addNewElementEvent)

4. **How do we change the labels in the database (e.g. "participantID")?**

- In the data_schema.js (as for writing down to the database) and 
- db_objects (as the class that front end uses to create a DB Object to be written down)


How can we set up a separate DB table for the element-level logging (individual button presses, clicks on images, etc.)?
5. **How do we write the logObject to the DB, and what changes are necessary if we want to add/delete/change variables in the log object in the future?**
Create a new schema in data_schema and a new class called logObject in db_objects. As for now, in the data_schema, the log is a lineOfData inside Participant schema. lineOfData structure is defined in db_objects.js
**Look into the data export code, in particular how much custom processing is done during the export (or is it just a matter of serializing the data fields?) How would we change the order of fields in the exported .csv file (since we may want to order the variables in the .csv file from most to least important)?**
The export code reuses Participants (a MongoDb collection) data. When a new session starts, a new participant will be created and written down to Participants collection in the database. Each participant instance is treated as a separate log in the export mode.
When the Export Mode is clicked, there will be a request to get all the participants and display as logs. The header of exported file is defined in advance as a constant and can be edited if necessary.
